document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'ie=edge\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'asset/all.css\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <footer class=\'footer\'>");
document.writeln("        <div class=\'footer-inner\'>");
document.writeln("            <h4>DEEPWAVE 2019 All Rights Reserved.</h4>");
document.writeln("            <ul class=\'footerlink\'>");
document.writeln("                <li><a href=\'\'>Privacy Policy</a></li>");
document.writeln("                <li><a href=\'\'>Web Map</a></li>");
document.writeln("            </ul>");
document.writeln("");
document.writeln("            <ul class=\'address\'>");
document.writeln("                <li>No.1, Sec. 4, Roosevelt Road, Taipei, 10617 Taiwan</li>");
document.writeln("                <li>+886-2-1234-1234</li>");
document.writeln("                <li>test@gmail.com</li>");
document.writeln("            </ul>");
document.writeln("");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </footer>");
document.writeln("</body>");