document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'en\'>");
document.writeln("");
document.writeln("<head>");
document.writeln("    <meta charset=\'UTF-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'ie=edge\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'asset/all.css\'>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("    <header class=\'header\'>");
document.writeln("        <div class=\'navbar\'>");
document.writeln("            <h1><a href=\'index.html\'>dwave</a></h1>");
document.writeln("            <ul class=\'menu-main\'>");
document.writeln("                <li><a href=\'main-tech.html\'>TECH</a></li>");
document.writeln("                <li><a href=\'page-about.html\'>ABOUT</a></li>");
document.writeln("                <li><a href=\'\'>JOIN</a></li>");
document.writeln("            </ul>");
document.writeln("            <div class=\'bar-icon\'>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("        <nav class=\'navbar-aside\'>");
document.writeln("            <div class=\'aside-close\'></div>");
document.writeln("            <div class=\'clearfix\'></div>");
document.writeln("            <ul class=\'aside-menu\'>");
document.writeln("                <li><a href=\'main-tech.html\'>TECH</a></li>");
document.writeln("                <li><a href=\'page-about.html\'>ABOUT</a></li>");
document.writeln("                <li><a href=\'#\'>JOIN</a></li>");
document.writeln("            </ul>");
document.writeln("        </nav>");
document.writeln("    </header>");
document.writeln("</body>");